---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-uninstall-pipelines

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: undeploy-sa
  namespace: mas-uninstall-pipelines

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: undeploy-sa
  namespace: mas-uninstall-pipelines
subjects:
  - kind: ServiceAccount
    name: undeploy-sa
    namespace: mas-uninstall-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mas-undeploy-sync-role
  generateName: "mas-undeploy-sync-role-"
  namespace: mas-uninstall-pipelines
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    "helm.sh/hook-weight": "10"
    checkov.io/skip1: CKV_K8S_20
    checkov.io/skip2: CKV_K8S_37
    checkov.io/skip3: CKV_K8S_40
    checkov.io/skip4: CKV_K8S_35
    checkov.io/skip5: CKV_K8S_43
    checkov.io/skip6: CKV_K8S_38
    checkov.io/skip7: CKV_K8S_13
    checkov.io/skip8: CKV_K8S_11
    checkov.io/skip9: CKV_K8S_10
    checkov.io/skip10: CKV_K8S_29
    checkov.io/skip11: CKV_K8S_28
    checkov.io/skip12: CKV_K8S_31
    checkov.io/skip13: CKV_K8S_30
    checkov.io/skip14: CKV_K8S_12
    checkov.io/skip15: CKV_K8S_23
    checkov.io/skip16: CKV_K8S_22
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        app: "mas-undeploy-job"
    spec:
      volumes:
        #- name: pv-storage
        #  persistentVolumeClaim:
        #    claimName: config-pvc
      containers:
        - name: mas-undeploy
          image: quay.io/ibmmas/cli:8.0.1-pre.ajw-nfsvpc
          imagePullPolicy: Always
          #volumeMounts:
          #  - mountPath: "/usr/config-pvc"
          #    name: pv-storage
          command:
            - /bin/sh
            - -c
            - |

              set -e

              echo "MAS_INSTANCE_ID=${MAS_INSTANCE_ID}"
              echo "DEPLOYMENT_FLAVOUR=${DEPLOYMENT_FLAVOUR}"
              DEPLOYMENT_FLAVOUR=${DEPLOYMENT_FLAVOUR:-"core"}

              if [ "${DEPLOYMENT_FLAVOUR}" == "core" ]; then
                echo "Inside helm pre-delete hook and uninstalling MAS Core instance"
                mas uninstall -i "${MAS_INSTANCE_ID}" --no-confirm
                for (( i=0; i<=15; i++ ));
                do
                varstr=$(oc get pr -n mas-${MAS_INSTANCE_ID}-pipelines | grep uninstall | awk -F' ' '{print $3}')
                if [[ $varstr == "Completed"  ]]; then
                echo "Uninstall pipeline has completed successfully"
                break
                elif [[ $varstr == "Running"  ]]; then
                echo "Uninstall pipeline is still running"
                sleep 120
                elif [[ $varstr == "Failed"  ]]; then
                echo "Uninstall pipeline has failed"
                exit
                fi
                done

              elif [ "${DEPLOYMENT_FLAVOUR}" == "manage" ]; then
                echo "Inside helm pre-delete hook and uninstalling MAS Core + Manage instance"
                mas uninstall -i "${MAS_INSTANCE_ID}" --no-confirm
                for (( i=0; i<=15; i++ ));
                do
                varstr=$(oc get pr -n mas-${MAS_INSTANCE_ID}-pipelines | grep uninstall | awk -F' ' '{print $3}')
                if [[ $varstr == "Completed"  ]]; then
                echo "Uninstall pipeline has completed successfully"
                break
                elif [[ $varstr == "Running"  ]]; then
                echo "Uninstall pipeline is still running"
                sleep 120
                elif [[ $varstr == "Failed"  ]]; then
                echo "Uninstall pipeline has failed"
                exit
                fi
                done
                oc delete project db2u
                sleep 600
              fi

          env:
            - name: MAS_INSTANCE_ID
              value: "{{ .Values.mas_instance_id }}"
            - name: DEPLOYMENT_FLAVOUR
              value: "{{ .Values.deployment_flavour }}"

      restartPolicy: Never
      serviceAccountName: undeploy-sa
  backoffLimit: 6